### ISSUE TITLE
Unable to run the Utility

### ISSUE THREAD

**Issue by arunshowryb** [Axway-API-Management-Plus/apimanager-report-tool#3]
Below is the run-metadata-export.bat , class path.

Error : Could not load the main class.

Appreciate any assistance. 

@echo off

IF NOT DEFINED JAVA_HOME GOTO :MissingJavaHome

SET currentDir=%cd%
SET programDir=%~dp0
SET bkpClassPath=%CLASSPATH%

CD %programDir%\..
SET CLASSPATH=C:\Users\lidagpq\.m2\repository;%programDir%..\conf

FOR /R ./lib %%a in (*.jar) DO CALL :AddToPath %%a

GOTO :OkClassPath

:AddToPath
SET CLASSPATH=%1;%CLASSPATH%
GOTO :EOF

:MissingJavaHome
ECHO "Environment variable JAVA_HOME not set!"
SET ERRNO=1
GOTO :END

:OkClassPath

CD %currentDir%

"%JAVA_HOME%\bin\java" -Xms64m -Xmx256m -classpath "%CLASSPATH%;C:\Users\lidagpq\.m2\repository;C:\HighmarkApps\apimanager-report-tool-develop\apimanager-report-tool-develop\target" com.axway.apim.report.APIManagerMetadataExport %*
echo %CLASSPATH%
SET ERRNO=%DEBUG%

:END
SET CLASSPATH=%bkpClassPath%

EXIT /B %ERRNO%

**Comment by cwiechmann** [comment]
Hi @arunshowryb, I suspect you have cloned the repository instead of downloading the release package. If this if the case, please download the latest release from [here](https://github.com/Axway-API-Management-Plus/apimanager-report-tool/releases) and start the script from there?

**Comment by arunshowryb** [comment]
Pulled down the release version..

My class path has C:\******\apimanager-report-tool-1.0.1\target;

Executed the script and printed classpath, the project just log4j.xml in the lib and no conf folder. 

My Maven are at C:\Users\*****\.m2\repository

C:\*********\apimanager-report-tool-1.0.1\src\main\assembly\scripts>run-metadata-export.bat -h localhost -u apiadmin -p changeme -f custom-policies -r ExcelAPISubscriptionReport
C:\*********\apimanager-report-tool-1.0.1\src\main\assembly\scripts\..\lib;C:\*********\apimanager-report-tool-1.0.1\src\main\assembly\scripts\..\conf
Error: Could not find or load main class com.axway.apim.report.APIManagerMetadataExport


Appreciate the assistance.

**Comment by cwiechmann** [comment]
Still looks like you pulled/cloned the project, instead of download a release package. `src/main/assembly`, etc. is the project source and used to build the release package.
You must download and use the release-package. The ZIP or TAR.GZ archive you can download from [here](https://github.com/Axway-API-Management-Plus/apimanager-report-tool/releases)
