### ISSUE TITLE
We need a custom report to pull "Custom Invoke Policy" for all APIs.

### ISSUE THREAD

**Issue by Arunabandari** [Axway-API-Management-Plus/apimanager-report-tool#4]
We have verified in all the available reports in the given apimanager-report-tool but we could not find any report which pulls Custom Invoke Policy for the APIs. We need  a custom report to pull "Custom Invoke Policy" for all APIs. Can you please help us to get that.

**Comment by cwiechmann** [comment]
Please use the API-Management CLI instead of this project to get that information.
You can get it from here:
https://github.com/Axway-API-Management-Plus/apim-cli/graphs/traffic

You may view the following page for more information:
https://github.com/Axway-API-Management-Plus/apim-cli/wiki/2.2-Export-and-report-APIs

**Comment by Arunabandari** [comment]
Thank you for the information !!.

I just tried through the given below link but unable to get the CLI tool. Can you help me how to get the CLI Tool.

https://github.com/Axway-API-Management-Plus/apim-cli/graphs/traffic

**Comment by cwiechmann** [comment]
Sorry, I picked the wrong deep link. You can get the latest release from here:
https://github.com/Axway-API-Management-Plus/apim-cli/releases/latest

**Comment by cwiechmann** [comment]
@Arunabandari, did you successfully created such a report with the APIM-CLI?

**Comment by Arunabandari** [comment]
Hello,

I did download the API - CLI and able to run the below command and got a report with all info but whatever i am looking for is not available in that. I am looking for specially the "Frontend API -> Inbound -> Inbound Security -> *Policy to invoke:" 

apim api get -s api-env -o csv -wide

We need this "*Policy to invoke" value as a column in my custom report for all the APIs. This is not available in the generated report. I gone through the given link https://github.com/Axway-API-Management-Plus/apim-cli/wiki/2.2-Export-and-report-APIs but could not find anything related this. 

So is there any command to pull the "Policy to invoke" value for all the APIs ?

**Comment by cwiechmann** [comment]
Ah, okay. Got it.
You are right, actually the Inbound-Security policy is not part of the report. Only Request-, Routing- and Response-Policies. However, good idea to add it.
Can you create an enhancement issue for the APIM-CLI and I will add it with the next release?

Im going to close this issue now. Feel free to create other requests if you miss anything in the CLI which is important for you.
